/*
* This Java source file was generated by the Gradle 'init' task.
*/
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;

class LibraryTest {

    Library testing = new Library();

    @Test
    public void roll() {
        int rollsNum = 4;
        assertEquals(rollsNum, testing.roll(rollsNum).length);
    }

    @Test
    public void containsDuplicates() {
        assertTrue(testing.containsDuplicates(new int[] { 1, 3, 4, 4 }));
    }

    @Test
    public void average() {
        assertEquals(3.25, testing.average(new int[] { 4, 5, 1, 3 }));
    }

    @Test
    public void lowestAverage() {
        assertArrayEquals(new int[] { 1, 2, 3, 4 },
                testing.lowestAverage(new int[][] { { 1, 2, 3, 4 }, { 1, 3, 5, 7 } }));
    }

    @Test
    void analyseWeather() {

        int[][] weeklyMonthTemperatures = { { 66, 64, 58, 65, 71, 57, 60 }, { 57, 65, 65, 70, 72, 65, 51 },
                { 55, 54, 60, 53, 59, 57, 61 }, { 65, 56, 55, 52, 55, 62, 57 } };

        String Expected = "\nNever saw temperature: 63" + "\nNever saw temperature: 67" + "\nNever saw temperature: 68"
                + "\nNever saw temperature: 69";

        assertEquals(Expected, testing.analyzingWeather(weeklyMonthTemperatures));

    }

    @Test
    void tally() {

        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String Expected = "Bush";

        assertEquals(Expected, testing.tally(votes));

    }

}
