/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static void main(String[] args) {
        System.out.println("Hello Abdelqader");
        Restaurant burgerRestaurant = new Restaurant("Macdonald", 2,2);

        Review review1 = new Review ("Abdelqader",4, "Good");
        Review review2 = new Review("Jack",5,"Perfect" );
        Review review3 = new Review("Sally",2,"" );

        System.out.println(burgerRestaurant);

        burgerRestaurant.addReview(review1);
        burgerRestaurant.addReview(review2);
        burgerRestaurant.addReview(review3);

        System.out.println(burgerRestaurant.getReviews());
        System.out.println(burgerRestaurant);



    }

}