/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void RestaurantName() {
        Restaurant restaurant=new Restaurant("Mcdonald's",4,2);
        assertEquals("Restaurant Name: Mcdonald's Rate: 4.0 Price Category: 2.0$" ,restaurant.toString());
    }
    @Test void RestaurantReview() {
        Review restaurant=new Review("Abdelqader",4,"good restaurant");
        assertEquals("Author: Abdelqader, rate: 4, notes: good restaurant" ,restaurant.toString());
    }
    @Test void multiReviews(){
        Restaurant restaurant=new Restaurant("Mcdonald's",4,2);
        Review review1 = new Review ("Abdelqader",4, "Good");
        Review review2 = new Review("Jack",5,"Perfect" );
        Review review3 = new Review("Sally",2,"not delicious as expected" );

        restaurant.addReview(review1);
        restaurant.addReview(review2);
        restaurant.addReview(review3);
        assertEquals("[Author: Abdelqader, rate: 4, notes: Good, Author: Jack, rate: 5, notes: Perfect, Author: Sally, rate: 2, notes: not delicious as expected]\n"+
        "Restaurant Name: Mcdonald's Rate: 3.6666667 Price Category: 2.0$",restaurant.getReviews().toString()+"\n"+ restaurant.toString());
    }
}
